### ISSUE TITLE
upstream CCSP fixed SRCREVs

### ISSUE THREAD

**Issue by bengardiner-at-irdeto** [IrdetoServices/meta-security-rockwell#1]
Builds of this project are specified against a fork of meta-rdk-belvedere which contains a commit that changes the SRCREVs of the many ccsp recipes to fixed SHA1s instead of autorevs

https://github.com/IrdetoServices/meta-rdk-belvedere/commit/c05cc7f09bfaa7f51fc0d2e72b4ec9819adf7825

When the ccsp recipes are left floating as autorevs, it is possible that builds fail due to updates to ccsp git repos without notice.

We should get a change into meta-rdk-belvedere to fix the ccsp recipe SRCREVs -- or otherwise achieve reproducible builds by some other means.

**Comment by BenGardiner** [comment]
This was resolved by PR #7

**Comment by bengardiner-at-irdeto** [comment]
This was resolved by PR #7
